### ISSUE TITLE
could not determine kind of name for C.gtk_scrolled_window_get_overlay_scrolling

### ISSUE THREAD

**Issue by jackman0** [gotk3/gotk3-examples#5]
I am attempting to run the examples, but I am getting this message on all that I've tried:

```
/home/jackman/opt/go/bin/go run /home/jackman/gopath/src/github.com/gotk3/gotk3-examples/gtk-examples/simple/simple.go
# github.com/gotk3/gotk3/gtk
could not determine kind of name for C.gtk_scrolled_window_get_overlay_scrolling
could not determine kind of name for C.gtk_scrolled_window_set_overlay_scrolling

Process finished with exit code 2
```

Is this a version issue on the libraries perhaps?

Thank you.

**Comment by EdwinHoksberg** [comment]
I'm getting the same error message. I am running Debian 8.6, I installed gotk3 with the command `go get -tags gtk_3_14 github.com/gotk3/gotk3/gtk` and my GTK version is `3.14.5-1+deb8u1`.

**Comment by peternavr** [comment]
I'm having the same issue on Debian 8.

**Comment by unkaktus** [comment]
Yes, you're all probably on Debian Jessie (GTK3.14). As specified here (https://github.com/gotk3/gotk3/wiki#installation) you should pass your GTK version in build tags. You should pass it everywhere since `gotk3` builds each time it's linked from other projects.
Build your application like `go build -tags gtk_3_14`. This solved this issue for me.
